// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vellum.Modules.Views;

#nullable disable

namespace Vellum.Modules.Views.Migrations
{
    [DbContext(typeof(ViewsDbContext))]
    [Migration("20260622161359_InitialViews")]
    partial class InitialViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("views")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vellum.Modules.Views.Entities.LayoutEdgeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RelationshipId")
                        .HasColumnType("uuid")
                        .HasColumnName("relationship_id");

                    b.Property<JsonDocument>("RoutePoints")
                        .HasColumnType("jsonb")
                        .HasColumnName("route_points");

                    b.Property<Guid>("ViewId")
                        .HasColumnType("uuid")
                        .HasColumnName("view_id");

                    b.HasKey("Id")
                        .HasName("pk_layout_edges");

                    b.HasIndex("ViewId", "RelationshipId")
                        .IsUnique()
                        .HasDatabaseName("ix_layout_edges_view_id_relationship_id");

                    b.ToTable("layout_edges", "views");
                });

            modelBuilder.Entity("Vellum.Modules.Views.Entities.LayoutPositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("element_id");

                    b.Property<Guid>("ViewId")
                        .HasColumnType("uuid")
                        .HasColumnName("view_id");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_layout_positions");

                    b.HasIndex("ViewId", "ElementId")
                        .IsUnique()
                        .HasDatabaseName("ix_layout_positions_view_id_element_id");

                    b.ToTable("layout_positions", "views");
                });

            modelBuilder.Entity("Vellum.Modules.Views.Entities.ViewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveFlowId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_flow_id");

                    b.Property<string>("ActiveLens")
                        .HasColumnType("text")
                        .HasColumnName("active_lens");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("RootElementId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_element_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.PrimitiveCollection<Guid[]>("VisibleElementIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("visible_element_ids");

                    b.HasKey("Id")
                        .HasName("pk_views");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_views_project_id");

                    b.ToTable("views", "views");
                });

            modelBuilder.Entity("Vellum.Modules.Views.Entities.LayoutEdgeEntity", b =>
                {
                    b.HasOne("Vellum.Modules.Views.Entities.ViewEntity", null)
                        .WithMany()
                        .HasForeignKey("ViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_layout_edges_views_view_id");
                });

            modelBuilder.Entity("Vellum.Modules.Views.Entities.LayoutPositionEntity", b =>
                {
                    b.HasOne("Vellum.Modules.Views.Entities.ViewEntity", null)
                        .WithMany()
                        .HasForeignKey("ViewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_layout_positions_views_view_id");
                });
#pragma warning restore 612, 618
        }
    }
}
