// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vellum.Modules.Modelling;

#nullable disable

namespace Vellum.Modules.Modelling.Migrations
{
    [DbContext(typeof(ModellingDbContext))]
    [Migration("20260625120000_AddElementIcon")]
    partial class AddElementIcon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("modelling")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vellum.Modules.Modelling.Entities.ElementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Branch")
                        .HasColumnType("uuid")
                        .HasColumnName("branch");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Technology")
                        .HasColumnType("text")
                        .HasColumnName("technology");

                    b.HasKey("Id")
                        .HasName("pk_elements");

                    b.HasIndex("ProjectId", "Branch")
                        .HasDatabaseName("ix_elements_project_id_branch");

                    b.HasIndex("ProjectId", "Branch", "ParentId")
                        .HasDatabaseName("ix_elements_project_id_branch_parent_id");

                    b.ToTable("elements", "modelling");
                });

            modelBuilder.Entity("Vellum.Modules.Modelling.Entities.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Branch")
                        .HasColumnType("uuid")
                        .HasColumnName("branch");

                    b.PrimitiveCollection<Guid[]>("ConsumerIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("consumer_ids");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProducerId")
                        .HasColumnType("uuid")
                        .HasColumnName("producer_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("SchemaId")
                        .HasColumnType("uuid")
                        .HasColumnName("schema_id");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("ProjectId", "Branch")
                        .HasDatabaseName("ix_messages_project_id_branch");

                    b.HasIndex("ProjectId", "Branch", "ProducerId")
                        .HasDatabaseName("ix_messages_project_id_branch_producer_id");

                    b.ToTable("messages", "modelling");
                });

            modelBuilder.Entity("Vellum.Modules.Modelling.Entities.RelationshipEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Branch")
                        .HasColumnType("uuid")
                        .HasColumnName("branch");

                    b.Property<Guid>("FromId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_id");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("LineShape")
                        .HasColumnType("text")
                        .HasColumnName("line_shape");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Technology")
                        .HasColumnType("text")
                        .HasColumnName("technology");

                    b.Property<Guid>("ToId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_id");

                    b.HasKey("Id")
                        .HasName("pk_relationships");

                    b.HasIndex("ProjectId", "Branch")
                        .HasDatabaseName("ix_relationships_project_id_branch");

                    b.ToTable("relationships", "modelling");
                });
#pragma warning restore 612, 618
        }
    }
}
