// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vellum.Modules.Scoring;

#nullable disable

namespace Vellum.Modules.Scoring.Migrations
{
    [DbContext(typeof(ScoringDbContext))]
    [Migration("20260624214310_InitialScoring")]
    partial class InitialScoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scoring")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vellum.Modules.Scoring.Entities.ScoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CriteriaResultsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("criteria_results_json");

                    b.Property<Guid>("DocId")
                        .HasColumnType("uuid")
                        .HasColumnName("doc_id");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doc_type");

                    b.Property<decimal>("OverallScore")
                        .HasColumnType("numeric")
                        .HasColumnName("overall_score");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ScoredBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scored_by");

                    b.Property<string>("SuggestedContent")
                        .HasColumnType("text")
                        .HasColumnName("suggested_content");

                    b.HasKey("Id")
                        .HasName("pk_scores");

                    b.HasIndex("DocId")
                        .HasDatabaseName("ix_scores_doc_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_scores_project_id");

                    b.ToTable("scores", "scoring");
                });
#pragma warning restore 612, 618
        }
    }
}
